# from typing import List

# from src.core.entities.user_token import UserTokenEntity


# class IUserTokenRepository(ABC):
#     async def add(self, token: UserTokenEntity) -> UserTokenEntity: ...
#     async def get_by_refresh_token(self, token_hash: str) -> UserTokenEntity | None: ...
#     async def revoke(self, token: UserTokenEntity) -> None: ...
#     async def revoke_all_for_user(self, user_id: int) -> None: ...
#     async def get_active_tokens_for_user(self, user_id: int) -> List[UserTokenEntity]: ...
